settings put system screen_off_timeout 2147483647
pm grant com.android.chrome android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.chrome android.permission.CAMERA
pm grant com.android.chrome android.permission.GET_ACCOUNTS
pm grant com.android.chrome android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.android.chrome android.permission.RECORD_AUDIO
pm grant com.android.chrome android.permission.READ_CONTACTS
pm grant com.android.vending android.permission.ACCESS_FINE_LOCATION
pm grant com.android.vending android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.vending android.permission.READ_CONTACTS
pm grant com.google.android.apps.assistant android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.assistant android.permission.CALL_PHONE
pm grant com.google.android.apps.assistant android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.assistant android.permission.READ_CONTACTS
pm grant com.google.android.apps.messaging android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.messaging android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.tachyon android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.tachyon android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.tachyon android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.tachyon android.permission.CAMERA
pm grant com.google.android.apps.tachyon android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.tachyon android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.tachyon android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.tachyon android.permission.RECORD_AUDIO
pm grant com.google.android.apps.tachyon android.permission.READ_CONTACTS
pm grant com.google.android.calendar android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.calendar android.permission.CALL_PHONE
pm grant com.google.android.dialer android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.dialer android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.dialer android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.dialer android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.dialer android.permission.ACCESS_BACKGROUND_LOCATION
pm grant com.google.android.gm.lite android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.gm.lite android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.youtube android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.youtube android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.youtube android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.youtube android.permission.READ_PHONE_STATE
pm grant com.google.android.youtube android.permission.CAMERA
pm grant com.google.android.youtube android.permission.GET_ACCOUNTS
pm grant com.google.android.youtube android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.youtube android.permission.RECORD_AUDIO
pm grant com.google.android.youtube android.permission.READ_CONTACTS
pm grant com.tcl.camera android.permission.ACCESS_FINE_LOCATION
pm grant com.tcl.camera android.permission.ACCESS_COARSE_LOCATION
pm grant com.tct.soundrecorder android.permission.READ_EXTERNAL_STORAGE
pm grant com.tct.soundrecorder android.permission.READ_PHONE_STATE
pm grant com.tct.soundrecorder android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.nbu.files android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.nbu.files android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.nbu.files android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.searchlite android.permission.READ_CALENDAR
pm grant com.google.android.apps.searchlite android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.searchlite android.permission.CALL_PHONE
pm grant com.google.android.apps.searchlite android.permission.CAMERA
pm grant com.google.android.apps.searchlite android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.searchlite android.permission.READ_CONTACTS
setprop debug.print.log false
setprop debug.tct.enable_monkey_log false
am broadcast -a com.debug.loggerui.ADB_CMD -e cmd_name start --ei cmd_target 1 -f 0x01000000
nohup sh /data/local/tmp/Mute.sh&
