settings put system screen_off_timeout 1
pm grant com.android.chrome android.permission.READ_EXTERNAL_STORAGE
pm grant com.android.chrome android.permission.CAMERA
pm grant com.android.chrome android.permission.GET_ACCOUNTS
pm grant com.android.chrome android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.android.chrome android.permission.RECORD_AUDIO
pm grant com.android.chrome android.permission.READ_CONTACTS
pm grant com.android.vending android.permission.ACCESS_COARSE_LOCATION
pm grant com.android.vending android.permission.READ_CONTACTS
pm grant com.android.vending android.permission.ACCESS_BACKGROUND_LOCATION
pm grant com.google.android.apps.maps android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.maps android.permission.CAMERA
pm grant com.google.android.apps.maps android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.maps android.permission.RECORD_AUDIO
pm grant com.google.android.apps.maps android.permission.READ_CONTACTS
pm grant com.google.android.apps.maps android.permission.ACCESS_MEDIA_LOCATION
pm grant com.google.android.apps.messaging android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.messaging android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.photos android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.photos android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.photos android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.photos android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.photos android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.photos android.permission.READ_CONTACTS
pm grant com.google.android.apps.walletnfcrel android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.apps.walletnfcrel android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.walletnfcrel android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.apps.walletnfcrel android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.walletnfcrel android.permission.CAMERA
pm grant com.google.android.apps.walletnfcrel android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.walletnfcrel android.permission.READ_CONTACTS
pm grant com.google.android.apps.walletnfcrel android.permission.ACCESS_BACKGROUND_LOCATION
pm grant com.google.android.apps.walletnfcrel android.permission.ACCESS_MEDIA_LOCATION
pm grant com.google.android.calendar android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.calendar android.permission.CALL_PHONE
pm grant com.google.android.contacts android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.gm android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.gm android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.youtube android.permission.ACCESS_FINE_LOCATION
pm grant com.google.android.youtube android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.youtube android.permission.ACCESS_COARSE_LOCATION
pm grant com.google.android.youtube android.permission.READ_PHONE_STATE
pm grant com.google.android.youtube android.permission.CAMERA
pm grant com.google.android.youtube android.permission.GET_ACCOUNTS
pm grant com.google.android.youtube android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.youtube android.permission.RECORD_AUDIO
pm grant com.google.android.youtube android.permission.READ_CONTACTS
pm grant com.jrdcom.filemanager android.permission.READ_EXTERNAL_STORAGE
pm grant com.jrdcom.filemanager android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tcl.camera android.permission.ACCESS_FINE_LOCATION
pm grant com.tcl.camera android.permission.ACCESS_COARSE_LOCATION
pm grant com.tcl.camera android.permission.ACCESS_BACKGROUND_LOCATION
pm grant com.tct.soundrecorder android.permission.READ_EXTERNAL_STORAGE
pm grant com.tct.soundrecorder android.permission.READ_PHONE_STATE
pm grant com.tct.soundrecorder android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.tachyon android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.apps.tachyon android.permission.READ_PHONE_STATE
pm grant com.google.android.apps.tachyon android.permission.WRITE_CONTACTS
pm grant com.google.android.apps.tachyon android.permission.CAMERA
pm grant com.google.android.apps.tachyon android.permission.WRITE_CALL_LOG
pm grant com.google.android.apps.tachyon android.permission.GET_ACCOUNTS
pm grant com.google.android.apps.tachyon android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.apps.tachyon android.permission.RECORD_AUDIO
pm grant com.google.android.apps.tachyon android.permission.READ_CONTACTS
pm grant com.google.android.apps.tachyon android.permission.ACCESS_MEDIA_LOCATION
pm grant com.google.android.googlequicksearchbox android.permission.ANSWER_PHONE_CALLS
pm grant com.google.android.googlequicksearchbox android.permission.READ_EXTERNAL_STORAGE
pm grant com.google.android.googlequicksearchbox android.permission.CAMERA
pm grant com.google.android.googlequicksearchbox android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.google.android.googlequicksearchbox android.permission.ACCESS_MEDIA_LOCATION
pm grant com.tcl.fmradio android.permission.RECORD_AUDIO
pm grant com.tcl.usercare android.permission.ACCESS_FINE_LOCATION
pm grant com.tcl.usercare android.permission.READ_EXTERNAL_STORAGE
pm grant com.tcl.usercare android.permission.ACCESS_COARSE_LOCATION
pm grant com.tcl.usercare android.permission.READ_PHONE_STATE
pm grant com.tcl.usercare android.permission.CAMERA
pm grant com.tcl.usercare android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.tcl.usercare android.permission.RECORD_AUDIO
pm grant com.tcl.usercare android.permission.ACCESS_BACKGROUND_LOCATION
pm grant com.tcl.usercare android.permission.ACCESS_MEDIA_LOCATION
pm grant com.tct.weather android.permission.ACCESS_FINE_LOCATION
pm grant com.tct.weather android.permission.ACCESS_COARSE_LOCATION
pm grant com.tct.weather android.permission.ACCESS_BACKGROUND_LOCATION
pm grant com.mobisystems.office android.permission.READ_EXTERNAL_STORAGE
pm grant com.mobisystems.office android.permission.READ_PHONE_STATE
pm grant com.mobisystems.office android.permission.WRITE_EXTERNAL_STORAGE
pm grant com.mobisystems.office android.permission.READ_CONTACTS
setprop debug.print.log false
setprop debug.tct.enable_monkey_log false
am startservice -n com.tcl.logger/com.tcl.logger.service.LogSwitchService -a com.tcl.logger.turnon
nohup sh /data/local/tmp/Mute.sh&
